/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TQuestions } from "./types";
export { TQuestions } from "./types";
export namespace Components {
    interface CmAssessment {
        "intro": string;
        /**
          * The name of the assessment
         */
        "name": string;
        /**
          * Data containing the assessment questions
         */
        "questions": TQuestions;
        /**
          * A URL-friendly identifier for the assessment
         */
        "slug": string;
    }
}
declare global {
    interface HTMLCmAssessmentElement extends Components.CmAssessment, HTMLStencilElement {
    }
    var HTMLCmAssessmentElement: {
        prototype: HTMLCmAssessmentElement;
        new (): HTMLCmAssessmentElement;
    };
    interface HTMLElementTagNameMap {
        "cm-assessment": HTMLCmAssessmentElement;
    }
}
declare namespace LocalJSX {
    interface CmAssessment {
        "intro"?: string;
        /**
          * The name of the assessment
         */
        "name"?: string;
        /**
          * Data containing the assessment questions
         */
        "questions"?: TQuestions;
        /**
          * A URL-friendly identifier for the assessment
         */
        "slug"?: string;
    }
    interface IntrinsicElements {
        "cm-assessment": CmAssessment;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cm-assessment": LocalJSX.CmAssessment & JSXBase.HTMLAttributes<HTMLCmAssessmentElement>;
        }
    }
}
