/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TQuestions, TRichText } from "./types";
export { TQuestions, TRichText } from "./types";
export namespace Components {
    interface CmAssessment {
        /**
          * Rich text introduction to the assessment
         */
        "intro": TRichText;
        /**
          * The name of the assessment
         */
        "name": string;
        /**
          * Data containing the assessment questions
         */
        "questions": TQuestions;
        /**
          * Rich text introduction for the results page
         */
        "resultsIntro": TRichText;
        /**
          * A URL-friendly identifier for the assessment
         */
        "slug": string;
    }
    interface CmRichText {
        "data": TRichText;
    }
}
declare global {
    interface HTMLCmAssessmentElement extends Components.CmAssessment, HTMLStencilElement {
    }
    var HTMLCmAssessmentElement: {
        prototype: HTMLCmAssessmentElement;
        new (): HTMLCmAssessmentElement;
    };
    interface HTMLCmRichTextElement extends Components.CmRichText, HTMLStencilElement {
    }
    var HTMLCmRichTextElement: {
        prototype: HTMLCmRichTextElement;
        new (): HTMLCmRichTextElement;
    };
    interface HTMLElementTagNameMap {
        "cm-assessment": HTMLCmAssessmentElement;
        "cm-rich-text": HTMLCmRichTextElement;
    }
}
declare namespace LocalJSX {
    interface CmAssessment {
        /**
          * Rich text introduction to the assessment
         */
        "intro"?: TRichText;
        /**
          * The name of the assessment
         */
        "name"?: string;
        /**
          * Data containing the assessment questions
         */
        "questions"?: TQuestions;
        /**
          * Rich text introduction for the results page
         */
        "resultsIntro"?: TRichText;
        /**
          * A URL-friendly identifier for the assessment
         */
        "slug"?: string;
    }
    interface CmRichText {
        "data"?: TRichText;
    }
    interface IntrinsicElements {
        "cm-assessment": CmAssessment;
        "cm-rich-text": CmRichText;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cm-assessment": LocalJSX.CmAssessment & JSXBase.HTMLAttributes<HTMLCmAssessmentElement>;
            "cm-rich-text": LocalJSX.CmRichText & JSXBase.HTMLAttributes<HTMLCmRichTextElement>;
        }
    }
}
